default : generate;

M4 = D:/proj/tools/build/win32/m4.exe

generate :
	$(M4) index.html4 > ../index.html
	$(M4) -D M4_TITLE="HTON" game_pre.html4 hton.html game_post.html4 > ../game/hton/index.html
	$(M4) -D M4_TITLE="Odd Gardens" game_pre.html4 oddgardens.html game_post.html4 > ../game/oddgardens/index.html
	$(M4) -D M4_TITLE="Perestroika 3D" game_pre.html4 perestroika3d.html game_post.html4 > ../game/perestroika3d/index.html
	$(M4) -D M4_TITLE="Al Dente" game_pre.html4 aldente.html game_post.html4 > ../game/aldente/index.html
	$(M4) -D M4_TITLE="Cursed Coin" game_pre.html4 cursedcoin.html game_post.html4 > ../game/cursedcoin/index.html
	$(M4) -D M4_TITLE="Crown Dungeon" game_pre.html4 crowndungeon.html game_post.html4 > ../game/crowndungeon/index.html
	$(M4) -D M4_TITLE="Chueue" game_pre.html4 chueue.html game_post.html4 > ../game/chueue/index.html
	$(M4) -D M4_TITLE="Witch's Well" game_pre.html4 witchswell.html game_post.html4 > ../game/witchswell/index.html
	$(M4) -D M4_TITLE="Beast's Castle" game_pre.html4 beastscastle.html game_post.html4 > ../game/beastscastle/index.html
